/* eslint-disable prettier/prettier */
export const SHOW_HOME_ADD_SHEET_SUCCESS = 'SHOW_HOME_ADD_SHEET_SUCCESS';
export const SHOW_BLUR_VIEW_SUCCESS = 'SHOW_BLUR_VIEW_SUCCESS';
export const TOGGLE_CUSTOM_PICKER_SUCCESS = 'TOGGLE_CUSTOM_PICKER_SUCCESS';
export const SHOW_SIDE_MENU = 'SHOW_SIDE_MENU';
